 *** CFD Status File Output ***

 CFD 2017 (Raven Production) [20160317]

 Job Name = Scenario 1   Date created: Thu Mar 16 22:05:58 2017


Created by Version: 17.0.20150327
*** Compressible ->advanced license required

LICENSE STATUS: Cloud id is empty using ADLM

LICENSE STATUS: Cloud id is empty using ADLM
 ###  ERROR: cfd_flomain.c 456 
 # Cannot checkout motion solver license: Failed to get feature authorization: Fail 
 ############################################## 
 
